### ISSUE TITLE
pip3 install -r requirements.txt errored out with exit status 1

### ISSUE THREAD

**Issue by 0-andy-0** [coursebuilder-ncl/makecourse#1]
Guess I am missing something obvious...

 pip install -r requirements.txt" gives errors:

Collecting MarkupSafe==1.0
  Using cached MarkupSafe-1.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/apt12/coursebuilder_env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/user/1001/pip-install-_2zqjmxa/MarkupSafe/setup.py'"'"'; __file__='"'"'/tmp/user/1001/pip-install-_2zqjmxa/MarkupSafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/user/1001/pip-pip-egg-info-lkot3u1l
         cwd: /tmp/user/1001/pip-install-_2zqjmxa/MarkupSafe/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/user/1001/pip-install-_2zqjmxa/MarkupSafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/home/apt12/coursebuilder_env/lib/python3.8/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by 0-andy-0** [comment]
OK fixed: change to MarkupSafe==1.1.0 in requirements.txt
(thanks to https://github.com/istresearch/scrapy-cluster/pull/234/files )

**Comment by christianp** [comment]
Thanks for spotting this. The latest version of Markupsafe is 1.1.1, so I'm using that.
