### ISSUE TITLE
MathJax doesn't process LaTeX inside say `\text{}`, `\textrm{}`, `\mbox{}`

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#101]
I have this:

```
Suppose we have the following propositions.
\begin{align*}
	p &: \text{``It is cold''}\\
	q &: \text{``It is raining''}\\
	r &: \text{``It is cold and raining''}
\end{align*}
```

In LaTeX it looks like this: 

![image](https://user-images.githubusercontent.com/5698564/133773787-69a228e9-124a-4ed1-912e-e11894b5f3c6.png)

In coursebuilder's web view it looks like this: 

![image](https://user-images.githubusercontent.com/5698564/133773820-1e0b801f-bc6d-40cf-b01f-25dec126d6e9.png)

Notice that the opening ` `` ` isn't rendered as a curly quote mark.

The makecourse HTML is

```
<p>
Suppose we have the following propositions. 
</p>
<span><script type="math/tex; mode=display">\begin{align*}  p & : \text{``It is cold''}\\ q & : \text{``It is raining''}\\ r & : \text{``It is cold and raining''} \end{align*}</script></span>
```

I think this looks okay, which made me think it might be MathJax's problem. I tried swapping the `\text{}` for `\textrm{}` and `\mbox{}` and the effect is the same. 

@christianp says this is because MathJax doesn't do anything with plain text and wonders if coursebuilder can do some processing. So I guess there may be broader issues than just this curly quote issue.

**Comment by georgestagg** [comment]
I've tweaked the MathJax settings in the default theme to load the `textmacros` MathJax extension[1]. That should hopefully help. With `textmacros` loaded, your example now looks like this in the web output:  

![Screenshot of example with quotes working](https://user-images.githubusercontent.com/982548/134011588-c14dd632-91e7-46cc-b643-22850c6fd100.png)

[1] http://docs.mathjax.org/en/latest/input/tex/extensions/textmacros.html
