### ISSUE TITLE
Accessibility: empty links - course index.html

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#12]
The automated accessibility checker [WAVE](https://wave.webaim.org/) is complaining about empty links on the course index.html page. It says to

> Remove the empty link or provide text within the link that describes the functionality and/or target of that link.

I guess this is referring to the links that contain only things like `<i class="fa fa-file-pdf-o"></i>`, which I don't totally understand. I guess you are replacing these tags with icons using CSS? Is it possible to put some text there which is blanked by CSS when the icon is placed? Or something else?

**Comment by christianp** [comment]
fixed by aded3b4bbd223ccd481b5ad365a5911f9ad03082
