### ISSUE TITLE
Instead of \alttext being an alternative to \alt, make it the way to do it everywhere

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#25]
`867ffaa` says:

> Includes changes to add an alias for \alt named \alttext since beamer also defines a macro called \alt for other reasons. Beamer's defintion should take precedence, so in beamer slides \alttext can be used as an alternative command to add alt text to images.

Can we just make `\alttext` the way to do this everywhere? It seems for such a new feature that having this be `\alt` except in beamer where it's `\alttext` as an alternative is unnecessarily confusing. Can we deprecate `\alt` now before it is widely used?

**Comment by extigy** [comment]
Good idea, it certainly does simplify things. I didn't want to pull it out from under your feet after just setting it up!

`\alt{}` deprecated and removed in favour of `\alttext{}` in c2f1ad149e57ddc75ee37d6e258c216261366091.

**Comment by prowlett** [comment]
That's good. I was concerned you might keep it for my benefit. To be clear: I'm trying to get things in order ready and anticipate issues, but won't start putting material together in earnest until I've returned from leave late August.
