### ISSUE TITLE
Beamer frame titles using \begin{frame}{Title goes here}

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#28]
Beamer frame titles can be written two ways. To produce something like this:

## Slide title
- This frame has a title.
- Or does it?

<hr>

I would expect to be able to do 

1

```
\documentclass{beamer} 
\begin{document}
\begin{frame}
\frametitle{Slide title}
\begin{itemize}
\item This frame has a title.
\item Or does it?
\end{itemize}
\end{frame}
\end{document}
```

or

2

```
\documentclass{beamer} 
\begin{document}
\begin{frame}{Slide title}
\begin{itemize}
\item This frame has a title.
\item Or does it?
\end{itemize}
\end{frame}
\end{document}
```

In Beamer, both work. In makecourse, only 1 works, 2 does not. Could this be easily fixed? (Certainly I can change my slides from 2 to 1 if necessary.)

**Comment by georgestagg** [comment]
Beamer titles and subtitles on `\begin{frame}` should now be supported as of commit 4ce9c5768529051609c95589f55ae5a535057672

**Comment by prowlett** [comment]
Yes, that works, thanks!
