### ISSUE TITLE
pdflatex crash: can makecourse report which file it was working on?

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#29]
When it has a problem with `pdflatex`, `makecourse` says this:

```
File "/home/.../coursebuilder_env/lib/python3.8/site-packages/makeCourse/latex.py", line 27, in runPdflatex
    raise Exception("Error: Something went wrong running pdflatex!")
Exception: Error: Something went wrong running pdflatex!
```

Is it possible for this to say which file it was trying to render when the exception was raised? This would help, because the information on fixing the error is found in the .log file for that .tex document. Often, this is the file you are working on and obvious, but there are cases where this is not case. For example, just now I updated `makecourse` and re-ran and it caused this error. It turns out I had an `\alt` command I wrote a couple of weeks ago that should now be `\alttext`, and it would have been helpful if it had reported on which .tex file it had crashed.

**Comment by georgestagg** [comment]
Implemented in 47a6a1b0ade4c68c82a807c9e8ac7e0f045091f0.
