### ISSUE TITLE
Incompatible with latest version of plasTeX

### ISSUE THREAD

**Issue by pnaaijkens** [coursebuilder-ncl/makecourse#30]
I'm trying out makecourse on a fresh install. The `requirements.txt` file pulls in the `master` branch of plasTeX. However it appears there have been some changes in the `plasTeX.Config` module. In particular it does not export a `config` object anymore, and some of the method names on the `ConfigManager` object have changed. Consequently, running `makecourse` leads to an exception here: https://github.com/coursebuilder-ncl/makecourse/blob/509a780351b87cb2d6a4ea32e54ac5c46906cc48/makeCourse/plastex/__init__.py#L15

Manually downgrading plasTeX to version 2.1 solved the issue for me (however I am not sure if this might lead to other issues).

**Comment by extigy** [comment]
Thanks for reporting this. As far as I know, using plasTeX version 2.1 directly should work okay. I have fixed the required version of plasTeX to v2.1 in `requirements.txt` and `setup.py`.

I'll update `makecourse` to work with the new `ConfigManager` object once the changes in `master` have been released in the next version of plasTeX.
