### ISSUE TITLE
"Warning: Problem copying Course's static directory!" meaning

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#32]
When I run makecourse (not verbose mode), it says "Warning: Problem copying Course's static directory!" twice. I have just been ignoring this, because what it produces seems fine in the end. However, I am wondering what this warning means and whether I am doing something wrong.

**Comment by georgestagg** [comment]
This message was safe to ignore. `makecourse` automatically copies the contents of a directory named `static` into the build tree. This is not so useful for LaTeX source, (where images are also automatically copied into the tree), but it is a useful feature for users writing markdown source where included files are not always automatically copied.

I updated the code to only try copying the directory if it exists, silencing the warning when the `static` directory does not exist. It should only show up now if something more serious is going wrong.
