### ISSUE TITLE
Coloured text in LaTeX (with the xcolor package)

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#36]
How do I do coloured text? For example, the following produces the PDF I would expect, but does not produce a HTML file with error `WARNING: No Python version of xcolor.sty was found`. Can xcolor be implemented, or should I be using a different method for coloured text?

```
\documentclass{article}
\usepackage{xcolor}
\begin{document}
This is a {\color{blue} blue} word.
\end{document}
```

**Comment by georgestagg** [comment]
There is no `xcolor` package in plaTeX right now. The `color` package should work, however, and IIRC supports `\color{}`.
