### ISSUE TITLE
BibTeX works, but could it be more automated?

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#37]
I can get BibTeX working by the following process but it is a bit clunky. 

I created a LaTeX file `bibtex.tex` like:

```
\documentclass{article}

\begin{document}
Hello \cite{rowlett}.

\bibliographystyle{apalike}
\bibliography{references}
\end{document}
```

And a BibTeX file `references.bib` like:

```
@article{rowlett,
    type = "article",
    author = "Peter Rowlett",
    year = "2020",
    title = {Programming as a mathematical activity},
    journal = "MSOR Connections",
    volume = "18",
    number = "2",
    pages = "13-17",
    url = "https://journals.gre.ac.uk/index.php/msor/article/view/1064"
}
```

I ran this through `makecourse` and it produced a PDF file like this:

> Hello [?].

and a HTML file like this:

> Hello [ .

However, if I first run it through `pdflatex bibtex.tex` and then `bibtex bibtex`, it creates a `.bbl` file. If I then run `makecourse` again, it produces better output:

PDF: 

> Hello [Rowlett, 2020].

HTML:

> Hello [ Rowlett, 2020 ] .

Since `makecourse` is happy to use the `.bbl` file, is there any chance it could create it as part of its process? 

One niggle that remains is that the PDF heading for the reference list is "References", but the HTML file produces this:

```
<div class="bibliography">
<h1>Bibliography</h1>
<h2>Bibliography</h2>
<ul class="bibliography">
<li id="rowlett" style="list-style: none"> <div class="bibcite">[Rowlett, 2020]</div> <p>
Rowlett, P. (2020). Programming as a mathematical activity. <em>MSOR Connections</em>, 18(2):13–17. 
</p>
</li>
</ul>
</div>
```

I don't need it to have two headings that are the same, and would prefer if they said "References" like the PDF.

**Comment by georgestagg** [comment]
This should now work better (including attempting to detect and run `bibtex` if required)  with 6567ee7e19071519d2971f451d6b46d25713a295.
