### ISSUE TITLE
Upgrade instructions

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#39]
Is it okay to update using the following?

```
pip install --upgrade git+https://github.com/coursebuilder-ncl/makecourse.git
```

It appears to work, but I wanted to check it didn't have consequences I haven't foreseen. 

If it is okay, could this be added to `README.md`?

**Comment by georgestagg** [comment]
As far as I know this should be okay, and I've added some instructions to `README.md`. The only thing I can think of is to ensure the coursebuilder virtualenv is active before running `pip install`.

If you find this does cause any trouble, let me know and I'll revisit.
