### ISSUE TITLE
appendixnumberbeamer: makecourse hangs without reporting error

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#40]
I have used the package `appendixnumberbeamer` in some beamer slides. This doesn't work. This isn't a major problem, it just allows you to have some slides at the end that don't contribute to the overall slides number.

A bigger problem is that `makecourse` just runs without ending or reporting an error. 

Here is example code:

```
\documentclass{beamer}
\usepackage{appendixnumberbeamer}

\begin{document}

\begin{frame}
\frametitle{Main slide}
\end{frame}

\appendix

\begin{frame}
\frametitle{Appendix slide}
\end{frame}

\end{document}
```

If I run this through `pdflatex`, it renders fine and produces two slides as expected. 

If I run it via `makecourse` having deleted the line `\appendix`, it works fine.

However, if I run `makecourse` with the `\appendix` command in place, it hangs. (It's been ten minutes now, and I'm going to crash it.)

If I run `makecourse -vv` it runs for a bit, then the last output generated is:

```
WARNING: No Python version of appendixnumberbeamer.sty was found
 ( /usr/local/texlive/2020/texmf-
   dist/tex/latex/appendixnumberbeamer/appendixnumberbeamer.sty
..... )....
WARNING: unrecognized command/environment: immediate
```

I don't regard it as essential to have a version of this package, but it would be nice if it crashed meaningfully (as other unsupported packages I've found have done). In fact, as the HTML version of the slides doesn't include page numbers, it would be good if it just ignores it.

**Comment by georgestagg** [comment]
A stub for `\appendixnumberbeamer` has been added in commit 67f2080dfd1c613dc3f5aef70664514181c444fd. This fixes the problem because the stub avoids loading the real package into plasTeX.

As you say, the HTML version of the slides doesn't need to worry about this package so the python version currently does nothing.
