### ISSUE TITLE
Is it possible to provide files for download?

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#42]
I would like to make available a file for students to download. I have tried something like this in a markdown file:

```
# File download 

Please [download the file](file.docx).
```

But when I ran `makecourse` it didn't copy the linked file across and ended up with a broken link.

I can fix this by moving `file.docx` into the folder with the generated HTML file like `build/default/.../file.docx` after running `makecourse`, or I could make a folder e.g. `/files/` and link to files in there using absolute links. But is there a better way to do this?

**Comment by georgestagg** [comment]
The way we've been handling this so far is to put files to download into a directory called `static`. If a directory named `static` exists, it is automatically copied recursively by `makecourse` to the build output directories.

Once you have placed a file in there you should be able to link to it with something like
```
Please [download the file](static/files/file.docx).
```
or, if you want to link to the file using `config.yml`:
```
- type: url
  title: Download the file
  source: static/files/file.docx
```

At some point in the future I would like to write a filter to catch these markdown links and automatically copy the files they reference, as is done for images. But at the moment such a scheme has not yet been implemented.

**Comment by prowlett** [comment]
Thanks, this sounds entirely suitable as a method. I have implemented it and it works great.

**Comment by prowlett** [comment]
Just a minor correction, unless I am doing something strange, I think you mean

```
Please [download the file](/static/files/file.docx).
```

Or, for LaTeX:

```
Please \hyperref{/static/files/file.docx}{download the file}.
```

(However, `config.yml` does not like the leading slash, preferring `source: static/files/file.docx` as you have it.)
