### ISSUE TITLE
Recent update breaks my course - plastex has problem with \newenvironment now?

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#53]
Help! I updated `makecourse` and ran it and now my course won't compile. I haven't changed the course. I used `makecourse -vv` and have narrowed down the problem to a line in a TeX file that uses `\newenvironment`. 

I have made a minimal example course that exhibits the same problem. 

I have two files: `config.yml` and `test-file.tex`. 

`config.yml`:

```
title: "Test module"
year: 2020/21
structure: 
    - type: part
      title: Just a basic part
      content:
        - type: chapter
          title: Test page
          source: test-file.tex
themes: 
  - title: Default
    source: default
    path: default
build_pdf: True
```

`test-file.tex`:

```
\documentclass{article}
\newenvironment{peter}{Start!}{End!}
\begin{document}
\begin{peter}
Middle!
\end{peter}
\end{document}
```

`makecourse -vv` runs until 

```
DEBUG: PlasTeX: test-file.tex
 ( .../coursebuilder_env/lib/python3.8/site-
   packages/plasTeX/Packages/article.py
ERROR: Could not load package "article": name 'Tokenizer' is not defined
ERROR: Error while expanding "newenvironment" in
   .../test-file.tex on line 2 (name
   'Tokenizer' is not defined)
ERROR: An error occurred while building the document object in
   .../test-file.tex on line 2 (name
   'Tokenizer' is not defined)
NameError: name 'Tokenizer' is not defined
```

Here is the result of running `ls -R build/default` excluding the `static` folder.

```
build/default/:
just_a_basic_part
static

build/default/just_a_basic_part/:
index.html
test_page

build/default/just_a_basic_part/test_page:
test_page.pdf
```

So it looks to me like the problem is with plastex generating the HTML version of `build/default/just_a_basic_part/test_page/test_page.pdf`, and it does not like the `\newenvironment` on line 2 of `test-file.tex`.

**Comment by georgestagg** [comment]
I made a change yesterday that required overriding plasTeX's `newcommand` and `newenvironment` functions, introducing a silly bug (forgetting to import something important) in `newenvironment`.

This should not have happened, my apologies. And thank you for the useful report.

The commit a8ab706296c3208fc6a2ac64bab2035d2f6cd227 should fix the problem. Do let me know if it has fixed it for your real content as well as the minimal example.

**Comment by prowlett** [comment]
Excellent, thank you for fixing this so quickly. It works, including for my real content.
