### ISSUE TITLE
makecourse updated to 7403238 doesn't look for LaTeX file in the right place and hangs

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#56]
I have updated to 7403238 and now `makecourse` does not run successfully. It hangs without error. I have not changed my course that happily compiled on Friday with commit 39d8381 installed. 

`makecourse -vv` goes through loading the theme, copying static files, cycles through the directory structure. It notices a few duplicate slugs and seems to deal with these happily. Then this happens:

```
makeCourse:process:241: INFO:	Establish when each item was last built
makeCourse:process:241: INFO:	Make PDFs
makeCourse.latex:exec:22: INFO:	Running pdflatex: module-info/module-info/schedule.tex
makeCourse.latex:exec:27: DEBUG:	This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)

makeCourse.latex:exec:27: DEBUG:	 restricted \write18 enabled.

makeCourse.latex:exec:27: DEBUG:	entering extended mode

makeCourse.latex:exec:27: DEBUG:	! I can't find file `module-info/schedule.tex'.

makeCourse.latex:exec:27: DEBUG:	<*> module-info/schedule.tex

makeCourse.latex:exec:27: DEBUG:	                            

makeCourse.latex:exec:27: DEBUG:	(Press Enter to retry, or Control-D to exit)
```

In relation to `makeCourse.latex:exec:22: INFO:	Running pdflatex: module-info/module-info/schedule.tex` - the input file is not at `module-info/module-info/schedule.tex`, it is at `module-info/schedule.tex`. The entry in `config.yml` is 

```
        - type: chapter
          title: Teaching schedule
          source: module-info/schedule.tex
```

In terms of output, a `build` folder is created, with a `default` theme within in (the only theme I am asking for) and a `static` folder within that, populated with the standard stuff and also what I put in `/static/` (actually `/static/files/` is copied to `/build/default/static/files`). `build` contains nothing else.

I can provide more information if this is helpful.

**Comment by georgestagg** [comment]
Apologies, I introduced a bug in 6567ee7e19071519d2971f451d6b46d25713a295. Does the latest commit fix the problem?
