### ISSUE TITLE
\includegraphics[scale=??] causes UnidentifiedImageError

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#61]
`makecourse` does not like `\includegraphics[scale=??]`. 

This builds fine:

```
\documentclass{article}
\usepackage{graphicx}
\begin{document}
\includegraphics{chessboard.pdf}
\end{document}
```

Whereas this...

```
\documentclass{article}
\usepackage{graphicx}
\begin{document}
\includegraphics[scale=0.5]{chessboard.pdf}
\end{document}
```

... is fine in `pdflatex` but in `makecourse` it causes an error 

```
UnidentifiedImageError: cannot identify image file '.../chessboard.pdf'
```

Can it support `scale`? At the very least, a more meaningful error would be helpful.

A workaround is to use `\includegraphics[width=0.5\textwidth]` or similar (which is what I tend to do - the above error identified by a colleague).

**Comment by prowlett** [comment]
@Alex-Corner FYI

**Comment by georgestagg** [comment]
This should work better in 7570838fd59a265812ca01ee2b132911c41d6b68. Notice a new prerequisite python package, PyPDF2. The command `pip install pypdf2` should pick it up with no bother.

**Comment by prowlett** [comment]
Updated and ran the example I cited above as not working, and it works. Thanks!
