### ISSUE TITLE
'Site last generated' date varies across site

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#67]
The bottom of each webpage says "Site last generated:", but because of commit 33a5a0c this is no longer accurate and different pages show different dates. I guess it should be something like "This page last generated:". Having different dates for different pages is useful, because the user can see whether a page has been changed since they last looked it, my problem here is just with the phrasing.

**Comment by georgestagg** [comment]
Good idea. I updated the wording in 14542793b6aac7c1b34a2c30a8aec93098e5ecac.
