### ISSUE TITLE
Style <blockquote> so quotes look distinct from normal paragraph text in HTML

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#99]
Please will you put some style on `<blockquote>`?

When I write this in Markdown

```
A wise man once said:

> In a hole in the ground there lived a hobbit.
```

it looks like this in my Markdown editor.

![Blockquote is indented, grey text preceded by a thick vertical bar](https://user-images.githubusercontent.com/5698564/133718724-68aee832-78e0-4c1e-a3a2-33692a01ef32.png)

In the PDF output it looks like this. I find the box a bit weird but okay, at least it stands out.

![Blockquote is inside a box](https://user-images.githubusercontent.com/5698564/133718769-75444d31-278b-46a1-98fa-06b1bde5ebfe.png)

Whereas in the HTML output it just looks like a normal paragraph. 

![Blockquote appears as normal text](https://user-images.githubusercontent.com/5698564/133718792-99d08bbe-0d2a-45b7-ba15-66ded954ef3f.png)

The quote is inside a `<blockquote>`, so presumably some style could be attached to that?

```
<p>A wise man once said:</p>
<blockquote>
<p>In a hole in the ground there lived a hobbit.</p>
</blockquote>
```

In LaTeX, using 

```
\begin{quote}
In a hole in the ground there lived a hobbit.
\end{quote}
```

looks like this in the PDF

![Blockquote is indented](https://user-images.githubusercontent.com/5698564/133719662-17f5a946-1fc9-48b8-b0e7-bb8122c9d432.png)

but still looks like normal text in the HTML
```
<p>
 A wise man once said: 
</p>
<blockquote class="quote"> In a hole in the ground there lived a hobbit. </blockquote>
```

Meanwhile, using 

```
\begin{quotation}
In a hole in the ground there lived a hobbit.
\end{quotation}
```

looks like this

![Blockquote is indented a bit more](https://user-images.githubusercontent.com/5698564/133719577-d0dc4f56-f97f-47f4-b4af-1c6ba2404f27.png)

(I don't really understand `quote` vs. `quotation`, but I think it's indented the same and also the first line is indented further)

and produces this HTML:

```
<p>
 A wise man once said: 
</p>
<blockquote class="quotation"> In a hole in the ground there lived a hobbit. </blockquote>
```

I'm not sure I would need a difference in style between `<blockquote>`, `<blockquote class="quote">` and `<blockquote class="quotation">`, but there may be some subtlety I'm missing.

**Comment by georgestagg** [comment]
I've added a CSS style for `blockquote` in the default theme in commit 6a9b37b.

Output from `pdflatex` will be as before, but HTML and markdown PDF output should now look something like this:

![Screenshot 2021-09-20 at 13 51 31](https://user-images.githubusercontent.com/982548/134005377-7e5815f9-83cc-469b-bf4f-c56d18411d22.png)

I've not styled based on the `quote` or `quotation` class, so both should pick it up.

**Comment by prowlett** [comment]
Brilliant, thanks! 

I first upgraded and it didn't work. I noticed that all the files in `build/default/static`, and indeed their counterparts in `coursebuilder_env/lib/python3.9/site-packages/makeCourse/themes/default/static` were last modified in May. So I ran the upgrade with `--force-reinstall` and now it works fine.
